"""ai_match_logs: signal breakdown, score_version, outcome_at for training data

Revision ID: 808db37efa9d
Revises: 013ddadd3602
Create Date: 2026-07-27 16:07:08.693577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808db37efa9d'
down_revision = '013ddadd3602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_match_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('score_version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('outcome_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_match_logs_candidate_id'), ['candidate_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_match_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_match_logs_candidate_id'))
        batch_op.drop_column('outcome_at')
        batch_op.drop_column('score_version')
        batch_op.drop_column('signals')

    # ### end Alembic commands ###
