"""add user.bio_embedding for semantic matching

Revision ID: c5f91b70db7f
Revises: dea9c01b257b
Create Date: 2026-06-26 10:10:11.403702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f91b70db7f'
down_revision = 'dea9c01b257b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio_embedding', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio_embedding')

    # ### end Alembic commands ###
