"""baseline schema

Revision ID: dea9c01b257b
Revises: 
Create Date: 2026-06-25 07:23:17.132844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea9c01b257b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('primary_sport', sa.String(length=20), nullable=True),
    sa.Column('sports', sa.String(length=120), nullable=True),
    sa.Column('court_count', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(length=120), nullable=True),
    sa.Column('lights', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('handle', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('primary_sport', sa.String(length=20), nullable=True),
    sa.Column('avatar_color', sa.String(length=120), nullable=True),
    sa.Column('avatar_fg', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_match_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viewer_id', 'candidate_id', 'sport', name='uq_match_log')
    )
    with op.batch_alter_table('ai_match_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_match_logs_viewer_id'), ['viewer_id'], unique=False)

    op.create_table('availability_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('time_band', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_of_week', 'time_band', name='uq_user_dow_band')
    )
    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_slots_user_id'), ['user_id'], unique=False)

    op.create_table('court_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('court_appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_appointments_court_id'), ['court_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_appointments_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_appointments_scheduled_at'), ['scheduled_at'], unique=False)

    op.create_table('court_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'user_id', name='uq_court_user_checkin')
    )
    with op.batch_alter_table('court_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_checkins_court_id'), ['court_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_checkins_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_checkins_user_id'), ['user_id'], unique=False)

    op.create_table('court_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'court_id', name='uq_user_court_fav')
    )
    with op.batch_alter_table('court_favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_favorites_court_id'), ['court_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_court_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('saved_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'player_id', name='uq_user_saved_player')
    )
    with op.batch_alter_table('saved_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_players_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_players_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_host_id'), ['host_id'], unique=False)

    op.create_table('sport_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('ntrp', sa.String(length=4), nullable=False),
    sa.Column('availability_summary', sa.String(length=200), nullable=True),
    sa.Column('home_court_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home_court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sport', name='uq_user_sport')
    )
    op.create_table('appointment_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('waitlisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['court_appointments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', 'user_id', name='uq_appt_user')
    )
    with op.batch_alter_table('appointment_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_participants_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_participants_user_id'), ['user_id'], unique=False)

    op.create_table('game_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decline_reason', sa.String(length=200), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_invites_invitee_id'), ['invitee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_invites_inviter_id'), ['inviter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_invites_phase'), ['phase'], unique=False)

    op.create_table('time_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invite_id'], ['game_invites.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_proposals_invite_id'), ['invite_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_proposals_invite_id'))

    op.drop_table('time_proposals')
    with op.batch_alter_table('game_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_invites_phase'))
        batch_op.drop_index(batch_op.f('ix_game_invites_inviter_id'))
        batch_op.drop_index(batch_op.f('ix_game_invites_invitee_id'))

    op.drop_table('game_invites')
    with op.batch_alter_table('appointment_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_participants_appointment_id'))

    op.drop_table('appointment_participants')
    op.drop_table('sport_profiles')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_host_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_guest_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('saved_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_players_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_players_player_id'))

    op.drop_table('saved_players')
    with op.batch_alter_table('court_favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_court_favorites_court_id'))

    op.drop_table('court_favorites')
    with op.batch_alter_table('court_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_checkins_user_id'))
        batch_op.drop_index(batch_op.f('ix_court_checkins_created_at'))
        batch_op.drop_index(batch_op.f('ix_court_checkins_court_id'))

    op.drop_table('court_checkins')
    with op.batch_alter_table('court_appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_appointments_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_court_appointments_creator_id'))
        batch_op.drop_index(batch_op.f('ix_court_appointments_court_id'))

    op.drop_table('court_appointments')
    with op.batch_alter_table('availability_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_slots_user_id'))

    op.drop_table('availability_slots')
    with op.batch_alter_table('ai_match_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_match_logs_viewer_id'))

    op.drop_table('ai_match_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('courts')
    # ### end Alembic commands ###
